<?php

require $cfg['server_path'] . "/mpgClasses.php";

if ( $_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['command']) ) {

	switch ($_POST['command']) {
			
		case 'get-credits':

			$output = array('result' => 'success', 'credits' => numOfCredits());
			exit(json_encode($output));

		break;
			
		case 'start-game':

			if (isset($_POST['names']) && isset($_POST['game'])) {
				
				$game = filter_var($_POST['game'], FILTER_SANITIZE_STRING);
				$game_type_id = getGameTypeID($game);
				$time = time();
				
				$game_data = array(
					"game_type_id" 	=> $game_type_id,
					"status"		=> 'in_progress',
					"player_count"	=> count($_POST['names']),
					"created_at"	=> $time,
					"updated_at"	=> $time
				);
				$insert = $db->prepare("INSERT INTO games (game_type_id, status, player_count, created_at, updated_at) VALUES (:game_type_id, :status, :player_count, :created_at, :updated_at)");
				$insert->execute($game_data);
				$game_id = $db->lastInsertId();
				
				foreach ($_POST['names'] as $name) {
					
					$player_name = filter_var($name, FILTER_SANITIZE_STRING);
					$score = 0;

					if ($game_type_id == 2) {
						$score = 30;
					}
					
					$player_data = array(
						"game_id"		=> $game_id,
						"name"			=> $player_name,
						"score"			=> $score,
						"created_at"	=> $time,
						"updated_at"	=> $time
					);
					$insertPl = $db->prepare("INSERT INTO players (game_id, name, score, created_at, updated_at) VALUES (:game_id, :name, :score, :created_at, :updated_at)");
					$insertPl->execute($player_data);
					
				}
				
				$output = array('result' => 'success', 'message' => "Game has been started");
				exit(json_encode($output));

			} else {
				
				$output = array('result' => 'error', 'message' => 'Invalid post values');
				exit (json_encode($output));
			}
			
		break;
			
		case 'end-clear-game':
			
			if (isset($_POST['game_id'])) {
				
				$game_id = filter_var($_POST['game_id'], FILTER_SANITIZE_STRING);
				
				$game_data = array(
					"game_id" 		=> $game_id,
					"status"		=> "incomplete",
					"updated_at"	=> time()
				);
				$update = $db->prepare("UPDATE `games` SET `status` = :status, `updated_at` = :updated_at WHERE `games`.`id` = :game_id");
				$update->execute($game_data);
				
				$output = array('result' => 'success', 'message' => "Game has been marked as incomplete");
				exit(json_encode($output));

			} else {
				
				$output = array('result' => 'error', 'message' => 'Invalid post values');
				exit (json_encode($output));
			}
			
		break;
			
		case 'complete-game':
			
			if (isset($_POST['game_id'])) {
				
				$game_id = filter_var($_POST['game_id'], FILTER_SANITIZE_STRING);
				
				$game_data = array(
					"game_id" 		=> $game_id,
					"status"		=> "in_progress",
					"updated_at"	=> time()
				);
				$update = $db->prepare("UPDATE `games` SET `status` = :status, `updated_at` = :updated_at WHERE `games`.`id` = :game_id");
				$update->execute($game_data);
				
				$output = array('result' => 'success', 'message' => "Game has been marked as completed");
				exit(json_encode($output));

			} else {
				
				$output = array('result' => 'error', 'message' => 'Invalid post values');
				exit (json_encode($output));
			}
			
		break;

		case 'payment':

			if (isset($_POST['card_number']) && isset($_POST['amount']) && isset($_POST['expiry_date'])) {

				/**************************** Request Variables *******************************/
				$store_id='store5';
				$api_token='yesguy';
				/************************* Transactional Variables ****************************/
				$type='purchase';
				$cust_id='cust id';
				$order_id='ord-'.date("dmy-G:i:s");
				$amount=$_POST['amount'];
				$pan='4242424242424242';
				$expiry_date='2011';
				$crypt='7';
				$dynamic_descriptor='123';
				$status_check = 'false';

				/*********************** Transactional Associative Array **********************/
				$txnArray=array('type'=>$type,
								'order_id'=>$order_id,
								'cust_id'=>$cust_id,
								'amount'=>$amount,
								'pan'=>$pan,
								'expdate'=>$expiry_date,
								'crypt_type'=>$crypt,
								'dynamic_descriptor'=>$dynamic_descriptor
								//,'wallet_indicator' => '' //Refer to documentation for details
								//,'cm_id' => '8nAK8712sGaAkls56' //set only for usage with Offlinx - Unique max 50 alphanumeric characters transaction id generated by merchant
							);
				/**************************** Transaction Object *****************************/
				$mpgTxn = new mpgTransaction($txnArray);
				/******************* Credential on File **********************************/
				$cof = new CofInfo();
				$cof->setPaymentIndicator("U");
				$cof->setPaymentInformation("2");
				$cof->setIssuerId("168451306048014");
				$mpgTxn->setCofInfo($cof);
				/****************************** Request Object *******************************/
				$mpgRequest = new mpgRequest($mpgTxn);
				$mpgRequest->setProcCountryCode("CA"); //"US" for sending transaction to US environment
				$mpgRequest->setTestMode(true); //false or comment out this line for production transactions
				/***************************** HTTPS Post Object *****************************/
				/* Status Check Example
				$mpgHttpPost  =new mpgHttpsPostStatus($store_id,$api_token,$status_check,$mpgRequest);
				*/
				$mpgHttpPost = new mpgHttpsPost($store_id,$api_token,$mpgRequest);
				/******************************* Response ************************************/
				$mpgResponse=$mpgHttpPost->getMpgResponse();
				print("\nCardType = " . $mpgResponse->getCardType());
				print("\nTransAmount = " . $mpgResponse->getTransAmount());
				print("\nTxnNumber = " . $mpgResponse->getTxnNumber());
				print("\nReceiptId = " . $mpgResponse->getReceiptId());
				print("\nTransType = " . $mpgResponse->getTransType());
				print("\nReferenceNum = " . $mpgResponse->getReferenceNum());
				print("\nResponseCode = " . $mpgResponse->getResponseCode());
				print("\nISO = " . $mpgResponse->getISO());
				print("\nMessage = " . $mpgResponse->getMessage());
				print("\nIsVisaDebit = " . $mpgResponse->getIsVisaDebit());
				print("\nAuthCode = " . $mpgResponse->getAuthCode());
				print("\nComplete = " . $mpgResponse->getComplete());
				print("\nTransDate = " . $mpgResponse->getTransDate());
				print("\nTransTime = " . $mpgResponse->getTransTime());
				print("\nTicket = " . $mpgResponse->getTicket());
				print("\nTimedOut = " . $mpgResponse->getTimedOut());
				print("\nStatusCode = " . $mpgResponse->getStatusCode());
				print("\nStatusMessage = " . $mpgResponse->getStatusMessage());
				print("\nHostId = " . $mpgResponse->getHostId());
				print("\nIssuerId = " . $mpgResponse->getIssuerId());
				print_r(implode(" ", $mpgResponse));

				if ($mpgResponse->getResponseCode() != "null" && $mpgResponse->getResponseCode() < 50) {
					// init the resource
					$ch = curl_init();

					curl_setopt_array(
						$ch, array(
						CURLOPT_URL => 'http://localhost:3030/game-data/1',
						CURLOPT_RETURNTRANSFER => true
						)
					);
						
					$output = curl_exec($ch);
					$game_data = json_decode($output, true);

					// If success update credits in DB
					$ch = curl_init("http://localhost:3030/game-data/1");
					# Setup request to send json via POST.
					$payload = json_encode( array( "credits" => $game_data['credits'] + 1 ) );
					curl_setopt( $ch, CURLOPT_POSTFIELDS, $payload );
					curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'PATCH');
					curl_setopt( $ch, CURLOPT_HTTPHEADER, array('Content-Type:application/json'));
					# Return response instead of printing.
					curl_setopt( $ch, CURLOPT_RETURNTRANSFER, true );
					# Send request.
					$result = curl_exec($ch);
					print($result);
					curl_close($ch);

					// Add transaction info to DB
					$ch = curl_init("http://localhost:3030/transactions");
					# Setup request to send json via POST.
					$payload = json_encode( array( "text" => "test" ) );
					curl_setopt( $ch, CURLOPT_POSTFIELDS, $payload );
					curl_setopt( $ch, CURLOPT_HTTPHEADER, array('Content-Type:application/json'));
					# Return response instead of printing.
					curl_setopt( $ch, CURLOPT_RETURNTRANSFER, true );
					# Send request.
					$result = curl_exec($ch);
					print($result);
					curl_close($ch);
				} else {
					// Return error message
				}
				
				// $output = array('result' => 'success', 'names' => $_SESSION['players'], 'count' => count($_SESSION['players']));
				// exit(json_encode($output));

			} else {
				
				$output = array('result' => 'error', 'message' => 'Error processing payment');
				exit (json_encode($output));
			}
			
		break;
			
		default :
			$output = array('result' => 'error', 'message' => 'Invalid command');
			exit (json_encode($output));
		break;
			
	}

}

?>